#!/usr/bin/env node
/**
 * Helper script to find your IP address and create .env file
 * Run: node setup-env.js
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      // Skip internal (loopback) and non-IPv4 addresses
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  
  return 'localhost';
}

const ipAddress = getLocalIP();
const envPath = path.join(__dirname, '.env');

console.log('🔍 Found your IP address:', ipAddress);
console.log('');

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env file already exists!');
  console.log('📝 Current contents:');
  console.log('─'.repeat(50));
  console.log(fs.readFileSync(envPath, 'utf8'));
  console.log('─'.repeat(50));
  console.log('');
  console.log('💡 To update, edit .env manually or delete it and run this script again.');
} else {
  const envContent = `# Mobile App Environment Configuration
# Auto-generated by setup-env.js

# Backend API URL
# Using your local IP address: ${ipAddress}
EXPO_PUBLIC_API_URL=http://${ipAddress}:3004

# Environment
ENVIRONMENT=dev

# Notes:
# - Make sure your backend server is running: cd website && npm run dev:mobile
# - Make sure your phone and computer are on the same WiFi network
# - For Android emulator, localhost works automatically
# - For iOS simulator or physical device, use the IP address above
`;

  fs.writeFileSync(envPath, envContent);
  console.log('✅ Created .env file!');
  console.log('');
  console.log('📋 Configuration:');
  console.log('   API URL: http://' + ipAddress + ':3004');
  console.log('');
  console.log('🚀 Next steps:');
  console.log('   1. Make sure backend is running: cd website && npm run dev:mobile');
  console.log('   2. Start mobile app: npm start');
  console.log('   3. If using physical device, ensure same WiFi network');
}

